### ISSUE TITLE
EN/EN: James Halliday - what you can build with a log #8

### ISSUE THREAD

**Issue by felipenmoura** [braziljs/subtitles#14]
Talk Transcription

Vídeo: https://www.youtube.com/watch?v=RPFjN1N148U&list=PLg2lQYZDBwORUpJTu5MxI71iEQIyc_Lno&index=14

**Comment by leandroferreira** [comment]
WIP @ http://amara.org/en/videos/yav6U8VaknWL/info/james-halliday-what-you-can-build-with-a-log-braziljs-2015/

**Comment by felipenmoura** [comment]
awesome.
I am already adding it to the video as transcription.
Could you open a pull request with the .srt file for the video, for us to have it stored.

**Comment by leandroferreira** [comment]
@felipenmoura sure, as soon as this is more advanced, I don't think is necessary to create a commit for this just yet.

**Comment by felipenmoura** [comment]
Ok, no problem.
I think, with the transcription, it will be easier and faster to have more translations...in this case, people will find it at amara to work...I believe it works pretty well
