### ISSUE TITLE
EN/EN e EN/PT: Jake Archibald - Instant loading offline-first progressive web apps the next generation part II uncovered

### ISSUE THREAD

**Issue by gnbezerra** [braziljs/subtitles#19]
I'm starting the transcription of Jake Archibald's keynote at BrazilJS Conf 2016.

As suggested in #17, I'm putting transcription, captioning (with timecodes) and translation in different issues, so someone can use the original text transcript (subproduct) to create the final product - the SRT in several languages.

**Comment by gnbezerra** [comment]
To tão acostumado a escrever em inglês que nem percebi que a descrição do grupo tá em português, haha

Concluído, assim que tiver os vídeos em HD eu faço as legendas EN e PT-BR com o tempo certinho.

**Comment by gnbezerra** [comment]
Estou fazendo as legendas em EN e PT-BR.

**Comment by jaydson** [comment]
@gbezerras ta fazendo já direto no YouTube?

**Comment by gnbezerra** [comment]
@jaydson to sim, fiz o download do vídeo e upload dele na minha conta do YouTube como privado pra poder fazer as legendas direto no YouTube. Assim que terminar eu baixo o srt e envio o pull request.

**Comment by jaydson** [comment]
@gbezerras, acho que tu não viu o que comentei na outra issue, eu liberei a edição nos vídeos originais no nosso canal.
http://www.youtube.com/timedtext_video?ref=share&v=k6P9ndFNarg

**Comment by gnbezerra** [comment]
@jaydson opa, ok! Vou fazer isso lá então, obrigado!

**Comment by gnbezerra** [comment]
Coloquei o EN/EN ontem lá, tô só esperando ser aprovado! PT-BR sai hoje, acredito.

**Comment by jaydson** [comment]
Publicado @gbezerras :)
