### ISSUE TITLE
TRANSCRIPT: Ruth John - Let's talk about MIDI

### ISSUE THREAD

**Issue by gnbezerra** [braziljs/subtitles#21]
Seguindo a série de palestras da BrazilJS, vou fazendo uma a uma conforme o meu tempo permitir. A próxima é a da Ruth John.

Por enquanto farei as transcrições, assim que tiver os vídeos finais, eu ou alguma outra pessoa podemos fazer as legendas.

**Comment by jaydson** [comment]
@gbezerras está ativado a contribuição da comunidade para a talk da Ruth:
http://www.youtube.com/timedtext_video?ref=share&v=ZB6kB2OEMdM
